spring.application.name=projeto-spring-jwt

# MySQL connection details

# Connection Homologation
#spring.datasource.url=jdbc:mysql://square-cloud-db-c14fc914e02347b99d31b7250aed7bd0.squareweb.app:7131/db_manicure
#spring.datasource.username=squarecloud
#spring.datasource.password=zd1fyBykxsMYrKjXmECAqV5m

# Connection prod
spring.datasource.url=jdbc:mysql://square-cloud-db-aaf0923fe8fd4519ab1983c618ebf4c9.squareweb.app:7201/db_manicure
spring.datasource.username=squarecloud
spring.datasource.password=o3VWpwtB4tfePGeAiDHDDn2u

# Connection Local
#spring.datasource.url=${DB_URL_DEV}
#spring.datasource.username=${DB_USERNAME_DEV}
#spring.datasource.password=${DB_PASSWORD_DEV}

# Driver JDBC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Optional settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Security Properties
security.config.prefix=Bearer
security.config.key=SECRET_KEY
security.config.expiration=3600000

jwt.secret=DDDFGFDSKKMMMMMMSAKALSMALDAGHGFJDLEEKEMDSSDADNFGBVVCC
jwt.expiration=3600000

#logs
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

#config port
server.port=80
server.address=0.0.0.0


