spring.application.name=projeto-spring-jwt

# MySQL connection details

# Connection Railway
spring.datasource.url=jdbc:mysql://crossover.proxy.rlwy.net:30476/db_manicure
spring.datasource.username=root
spring.datasource.password=mmircGJOOfdDjwRHgQFeCUfAQaSqpJwJ

# Connection Local
#spring.datasource.url=${DB_URL_DEV}
#spring.datasource.username=${DB_USERNAME_DEV}
#spring.datasource.password=${DB_PASSWORD_DEV}

# Driver JDBC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Optional settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Security Properties
security.config.prefix=Bearer
security.config.key=SECRET_KEY
security.config.expiration=3600000

jwt.secret=DDDFGFDSKKMMMMMMSAKALSMALDAGHGFJDLEEKEMDSSDADNFGBVVCC
jwt.expiration=3600000

#logs
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG




